DROP TABLE IF EXISTS DEPARTMENT;
DROP TABLE IF EXISTS EMPLOYEES;

CREATE TABLE DEPARTMENT
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DEPARTMENTNAME VARCHAR(2147483647) NOT NULL
);
CREATE UNIQUE INDEX "DEPARTMENT_ID_uindex" ON DEPARTMENT (ID);
CREATE UNIQUE INDEX "DEPARTMENT_DEPARTMENTNAME_uindex" ON DEPARTMENT (DEPARTMENTNAME);

CREATE TABLE EMPLOYEES
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DEPARTMENT_ID BIGINT NOT NULL,
    FULLNAME VARCHAR(2147483647) NOT NULL,
    BIRTHDAY DATE,
    SALARY INT NOT NULL,
    CONSTRAINT EMPLOYEES_DEPARTMENT__FK FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT (ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "EMPLOYEES_ID_uindex" ON EMPLOYEES (ID);
CREATE INDEX EMPLOYEES_DEPARTMENT__FK_INDEX_8 ON EMPLOYEES (DEPARTMENT_ID);
